const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const budgetSchema = new Schema({
  budgetName: { type: String, required: true },
  startDate: { type: Date, required: true },
  endDate: { type: Date, required: true },
  incomeCategories: {
    revenue: { type: Number, default: 0 },
    sales: { type: Number, default: 0 },
    interestIncome: { type: Number, default: 0 },
    otherIncome: { type: Number, default: 0 },
  },
  expenseCategories: {
    salariesAndWages: { type: Number, default: 0 },
    rentLease: { type: Number, default: 0 },
    utilities: { type: Number, default: 0 },
    suppliesAndMaterials: { type: Number, default: 0 },
    marketingAndAdvertising: { type: Number, default: 0 },
    travelAndEntertainment: { type: Number, default: 0 },
    maintenanceAndRepairs: { type: Number, default: 0 },
    insurancePremiums: { type: Number, default: 0 },
    taxes: { type: Number, default: 0 },
    interestExpense: { type: Number, default: 0 },
    depreciationAndAmortization: { type: Number, default: 0 },
  },
  budgetAmounts: {
    revenue: { type: Number, default: 0 },
    sales: { type: Number, default: 0 },
    interestIncome: { type: Number, default: 0 },
    otherIncome: { type: Number, default: 0 },
    salariesAndWages: { type: Number, default: 0 },
    rentLease: { type: Number, default: 0 },
    utilities: { type: Number, default: 0 },
    suppliesAndMaterials: { type: Number, default: 0 },
    marketingAndAdvertising: { type: Number, default: 0 },
    travelAndEntertainment: { type: Number, default: 0 },
    maintenanceAndRepairs: { type: Number, default: 0 },
    insurancePremiums: { type: Number, default: 0 },
    taxes: { type: Number, default: 0 },
    interestExpense: { type: Number, default: 0 },
    depreciationAndAmortization: { type: Number, default: 0 },
  },
  actualAmounts: {
    revenue: { type: Number, default: 0 },
    sales: { type: Number, default: 0 },
    interestIncome: { type: Number, default: 0 },
    otherIncome: { type: Number, default: 0 },
    salariesAndWages: { type: Number, default: 0 },
    rentLease: { type: Number, default: 0 },
    utilities: { type: Number, default: 0 },
    suppliesAndMaterials: { type: Number, default: 0 },
    marketingAndAdvertising: { type: Number, default: 0 },
    travelAndEntertainment: { type: Number, default: 0 },
    maintenanceAndRepairs: { type: Number, default: 0 },
    insurancePremiums: { type: Number, default: 0 },
    taxes: { type: Number, default: 0 },
    interestExpense: { type: Number, default: 0 },
    depreciationAndAmortization: { type: Number, default: 0 },
  },
  variance: {
    revenue: { type: Number, default: 0 },
    sales: { type: Number, default: 0 },
    interestIncome: { type: Number, default: 0 },
    otherIncome: { type: Number, default: 0 },
    salariesAndWages: { type: Number, default: 0 },
    rentLease: { type: Number, default: 0 },
    utilities: { type: Number, default: 0 },
    suppliesAndMaterials: { type: Number, default: 0 },
    marketingAndAdvertising: { type: Number, default: 0 },
    travelAndEntertainment: { type: Number, default: 0 },
    maintenanceAndRepairs: { type: Number, default: 0 },
    insurancePremiums: { type: Number, default: 0 },
    taxes: { type: Number, default: 0 },
    interestExpense: { type: Number, default: 0 },
    depreciationAndAmortization: { type: Number, default: 0 },
  },
  notesComments: { type: String },
  approvalStatus: {
    type: String,
    enum: ["Pending", "Approved", "Rejected"],
    default: "Pending",
  },
  currency: {
    type: String,
    enum: ["EUR", "DOL", "JPY", "BRL"],
    default: "EUR",
  },
});

const Budget = mongoose.model("Budget", budgetSchema);

module.exports = Budget;
